# Generated by Django 4.1.7 on 2023-03-16 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_destination_remove_guides_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='ExtraDestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.destination')),
            ],
        ),
    ]
