# Generated by Django 4.1.7 on 2023-03-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_destination_image_extradestinationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='about',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
