# Generated by Django 4.1.7 on 2023-03-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_customuser_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extradestinationimage',
            old_name='Destination',
            new_name='destination',
        ),
    ]
