# Generated by Django 4.1.7 on 2023-03-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_guides_bio_alter_guides_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='type',
            field=models.CharField(default='Mega City', max_length=255),
            preserve_default=False,
        ),
    ]
