# Generated by Django 4.1.7 on 2023-03-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_customuser_bio_customuser_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='short_info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
