# Generated by Django 4.1.7 on 2023-03-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_destination_short_info_destination_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='short_info',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
