# Generated by Django 4.1.7 on 2023-03-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_alter_destination_short_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='short_info',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
