# Generated by Django 4.1.7 on 2023-03-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_alter_destination_short_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
