# Generated by Django 4.1.7 on 2023-03-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_alter_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_end_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_start_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
