# Generated by Django 4.1.7 on 2023-04-03 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_booking_is_booked_alter_booking_is_end_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_accepted',
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='API.booking'),
        ),
    ]
