# Generated by Django 4.1.7 on 2023-04-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_remove_booking_is_accepted_alter_payment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidepayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
