# Generated by Django 4.1.7 on 2023-04-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_alter_guidepayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(default='PayPal', max_length=100),
            preserve_default=False,
        ),
    ]
