# Generated by Django 4.1.7 on 2023-04-05 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_booking_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.destination'),
        ),
    ]
