# Generated by Django 4.2 on 2023-04-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0027_chat_message'),
        ('API', '0028_message'),
    ]

    operations = [
    ]
