# Generated by Django 4.2 on 2023-04-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0030_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
